// apps/editor/src/app/components/canvas/canvas.component.ts
import { AfterViewChecked, ChangeDetectionStrategy, Component, ElementRef, Input, OnInit, ViewChild } from '@angular/core';

@Component({
  selector: 'app-canvas',
  templateUrl: './canvas.component.html',
  styleUrls: ['./canvas.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class CanvasComponent implements OnInit, AfterViewChecked {

  @Input() width: number;
  @Input() height: number;

  @ViewChild('canvas', { static: true }) canvas!: ElementRef<HTMLCanvasElement>;

  constructor(private elementRef: ElementRef) { }

  ngOnInit() { }

  ngAfterViewChecked() {
    this.width = this.elementRef.nativeElement.width;
    this.height = this.elementRef.nativeElement.height;
  }


  getContext(context: string) {
    return this.canvas.nativeElement.getContext(context);
  }

  get webglContext() {
    return this.canvas.nativeElement.getContext('webgl') as WebGLRenderingContext;
  }

  get webgl2Context() {
    return this.canvas.nativeElement.getContext(
      'webgl2'
    ) as WebGL2RenderingContext;
  }

  get canvasElement() {
    return this.canvas;
  }

}
<canvas #canvas class="canvas" [width]="width" [height]="height" (mousedown)="mouseDown($event)"
  (mouseup)="mouseUp($event)">
</canvas>

// src/components/canvas/Canvas.tsx
import React, { Component, createRef } from 'react';
import './canvas.css';

interface AppProps {
  width?: number;
  height?: number;
}
interface AppState {}

export class Canvas extends Component<AppProps, AppState> {
  private canvasRef = createRef<HTMLCanvasElement>();

  constructor(props: any) {
    super(props);
  }

  getContext(context: string) {
    return this.canvasRef.current!.getContext(context);
  }

  get webglContext() {
    return this.canvasRef.current!.getContext('webgl') as WebGLRenderingContext;
  }

  get webgl2Context() {
    return this.canvasRef.current!.getContext(
      'webgl2'
    ) as WebGL2RenderingContext;
  }

  get canvasElement() {
    return this.canvasRef.current;
  }

  render() {
    return (
      <canvas
        ref={this.canvasRef}
        className='canvas'
        width={this.props.width}
        height={this.props.height}
      />
    );
  }
}
